version: '3.8'
services:
  backend:
    build:
      context: ./backend
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      MYSQL_HOST: localhost
      MYSQL_USER: user
      MYSQL_PASSWORD: 011007
      MYSQL_DB: counter_db
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    ports:
      - "80:80"
      - "443:443"
    networks:
      - app-network

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
      - frontend
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: counter_db
      MYSQL_USER: user
      MYSQL_PASSWORD: 011007
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./counter_db.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge